### ISSUE TITLE
Add Options Class

### ISSUE THREAD

**Issue by canhkieu** [brunoseco/vue-pagination-bootstrap#3]
I wanna custom css class for ul element. Please add this feature.

**Comment by brunoseco** [comment]
thanks for contribute...

add on commit https://github.com/brunoseco/vue-pagination-bootstrap/commit/b4a5da6c6291febb1ac3162cf071bb6db53d7f36

**Comment by brunoseco** [comment]
thanks for contribute...

add on commit https://github.com/brunoseco/vue-pagination-bootstrap/commit/b4a5da6c6291febb1ac3162cf071bb6db53d7f36
